### ISSUE TITLE
前端页面怎么修改

### ISSUE THREAD

**Issue by bejea** [ouqiang/gocron#54]
我打算基于你的版本做点二次开发，不知道前端页面修改后如何生效的，做了以下尝试：
1. 使用你提供的二进制版本直接运行，修改templates下的静态页面，不生效，即使我把这个文件夹改名也不影响项目运行，奇怪。
2. 使用源码，对vue模版文件进行修改，然后重新编译前 cd web/vue && yarn run build，提示错误：
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/farmer/igo/src/github.com/bejea/gocron/web/vue/build/check-versions.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
error Command failed with exit code 1.

看了下目录结构源码中不存在这个文件夹internal/modules/cjs

对vue不熟，望指点下

**Comment by ouqiang** [comment]
本地开发， 需要用node转发到 gocron

yarn run dev   启动node server    
./bin/gocron web -e dev 启动gocron

 http://localhost:8080访问

**Comment by bejea** [comment]
谢谢，花了点时间补了node和webpack的知识，现在用node起服务调go的api开发和发布都OK了。
还有个问题，就是单独使用go本身5920端口运行服务时使用的前端页面哪里的，我本以为应该是 public/templates,但是修改甚至删除厘米页面都没效果。疑惑！

**Comment by ouqiang** [comment]
public/templates 是旧版本服务端渲染模板，已经弃用了，目前服务端渲染改为客户端渲染的工作还没完成，所以没删除。最终发布时，静态文件被嵌入到二进制文件中了。查看makefile中package目标，描述了发布打包流程。
